package com.zw.domain;

public class activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.id
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.owner
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.name
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.start_date
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    private String start_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.end_date
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    private String end_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.cost
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    private String cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.description
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.create_time
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    private String create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.create_by
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    private String create_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.edit_time
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    private String edit_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity.edit_by
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    private String edit_by;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity.id
     *
     * @return the value of tbl_activity.id
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity.id
     *
     * @param id the value for tbl_activity.id
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity.owner
     *
     * @return the value of tbl_activity.owner
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity.owner
     *
     * @param owner the value for tbl_activity.owner
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity.name
     *
     * @return the value of tbl_activity.name
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity.name
     *
     * @param name the value for tbl_activity.name
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity.start_date
     *
     * @return the value of tbl_activity.start_date
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public String getStart_date() {
        return start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity.start_date
     *
     * @param start_date the value for tbl_activity.start_date
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public void setStart_date(String start_date) {
        this.start_date = start_date == null ? null : start_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity.end_date
     *
     * @return the value of tbl_activity.end_date
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public String getEnd_date() {
        return end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity.end_date
     *
     * @param end_date the value for tbl_activity.end_date
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public void setEnd_date(String end_date) {
        this.end_date = end_date == null ? null : end_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity.cost
     *
     * @return the value of tbl_activity.cost
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public String getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity.cost
     *
     * @param cost the value for tbl_activity.cost
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public void setCost(String cost) {
        this.cost = cost == null ? null : cost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity.description
     *
     * @return the value of tbl_activity.description
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity.description
     *
     * @param description the value for tbl_activity.description
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity.create_time
     *
     * @return the value of tbl_activity.create_time
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public String getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity.create_time
     *
     * @param create_time the value for tbl_activity.create_time
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public void setCreate_time(String create_time) {
        this.create_time = create_time == null ? null : create_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity.create_by
     *
     * @return the value of tbl_activity.create_by
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public String getCreate_by() {
        return create_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity.create_by
     *
     * @param create_by the value for tbl_activity.create_by
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public void setCreate_by(String create_by) {
        this.create_by = create_by == null ? null : create_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity.edit_time
     *
     * @return the value of tbl_activity.edit_time
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public String getEdit_time() {
        return edit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity.edit_time
     *
     * @param edit_time the value for tbl_activity.edit_time
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public void setEdit_time(String edit_time) {
        this.edit_time = edit_time == null ? null : edit_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity.edit_by
     *
     * @return the value of tbl_activity.edit_by
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public String getEdit_by() {
        return edit_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity.edit_by
     *
     * @param edit_by the value for tbl_activity.edit_by
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    public void setEdit_by(String edit_by) {
        this.edit_by = edit_by == null ? null : edit_by.trim();
    }
}