package com.zw.domain;

public class Clue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.id
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.fullname
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.appellation
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String appellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.owner
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.company
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.job
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.email
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.phone
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.website
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.mphone
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String mphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.state
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.source
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.create_by
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String create_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.create_time
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.edit_by
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String edit_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.edit_time
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String edit_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.description
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.contact_summary
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String contact_summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.next_contact_time
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String next_contact_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue.address
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.id
     *
     * @return the value of tbl_clue.id
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.id
     *
     * @param id the value for tbl_clue.id
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.fullname
     *
     * @return the value of tbl_clue.fullname
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.fullname
     *
     * @param fullname the value for tbl_clue.fullname
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.appellation
     *
     * @return the value of tbl_clue.appellation
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getAppellation() {
        return appellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.appellation
     *
     * @param appellation the value for tbl_clue.appellation
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setAppellation(String appellation) {
        this.appellation = appellation == null ? null : appellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.owner
     *
     * @return the value of tbl_clue.owner
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.owner
     *
     * @param owner the value for tbl_clue.owner
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.company
     *
     * @return the value of tbl_clue.company
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.company
     *
     * @param company the value for tbl_clue.company
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.job
     *
     * @return the value of tbl_clue.job
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.job
     *
     * @param job the value for tbl_clue.job
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.email
     *
     * @return the value of tbl_clue.email
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.email
     *
     * @param email the value for tbl_clue.email
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.phone
     *
     * @return the value of tbl_clue.phone
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.phone
     *
     * @param phone the value for tbl_clue.phone
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.website
     *
     * @return the value of tbl_clue.website
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.website
     *
     * @param website the value for tbl_clue.website
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.mphone
     *
     * @return the value of tbl_clue.mphone
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getMphone() {
        return mphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.mphone
     *
     * @param mphone the value for tbl_clue.mphone
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setMphone(String mphone) {
        this.mphone = mphone == null ? null : mphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.state
     *
     * @return the value of tbl_clue.state
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.state
     *
     * @param state the value for tbl_clue.state
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.source
     *
     * @return the value of tbl_clue.source
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.source
     *
     * @param source the value for tbl_clue.source
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.create_by
     *
     * @return the value of tbl_clue.create_by
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getCreate_by() {
        return create_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.create_by
     *
     * @param create_by the value for tbl_clue.create_by
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setCreate_by(String create_by) {
        this.create_by = create_by == null ? null : create_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.create_time
     *
     * @return the value of tbl_clue.create_time
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.create_time
     *
     * @param create_time the value for tbl_clue.create_time
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setCreate_time(String create_time) {
        this.create_time = create_time == null ? null : create_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.edit_by
     *
     * @return the value of tbl_clue.edit_by
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getEdit_by() {
        return edit_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.edit_by
     *
     * @param edit_by the value for tbl_clue.edit_by
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setEdit_by(String edit_by) {
        this.edit_by = edit_by == null ? null : edit_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.edit_time
     *
     * @return the value of tbl_clue.edit_time
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getEdit_time() {
        return edit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.edit_time
     *
     * @param edit_time the value for tbl_clue.edit_time
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setEdit_time(String edit_time) {
        this.edit_time = edit_time == null ? null : edit_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.description
     *
     * @return the value of tbl_clue.description
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.description
     *
     * @param description the value for tbl_clue.description
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.contact_summary
     *
     * @return the value of tbl_clue.contact_summary
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getContact_summary() {
        return contact_summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.contact_summary
     *
     * @param contact_summary the value for tbl_clue.contact_summary
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setContact_summary(String contact_summary) {
        this.contact_summary = contact_summary == null ? null : contact_summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.next_contact_time
     *
     * @return the value of tbl_clue.next_contact_time
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getNext_contact_time() {
        return next_contact_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.next_contact_time
     *
     * @param next_contact_time the value for tbl_clue.next_contact_time
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setNext_contact_time(String next_contact_time) {
        this.next_contact_time = next_contact_time == null ? null : next_contact_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.address
     *
     * @return the value of tbl_clue.address
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.address
     *
     * @param address the value for tbl_clue.address
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}