package com.zw.domain;

public class Contacts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.id
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.owner
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.source
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.customer_id
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String customer_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.fullname
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.appellation
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String appellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.email
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.mphone
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String mphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.job
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.create_by
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String create_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.create_time
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.edit_by
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String edit_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.edit_time
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String edit_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.description
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.contact_summary
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String contact_summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.next_contact_time
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String next_contact_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.address
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.id
     *
     * @return the value of tbl_contacts.id
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.id
     *
     * @param id the value for tbl_contacts.id
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.owner
     *
     * @return the value of tbl_contacts.owner
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.owner
     *
     * @param owner the value for tbl_contacts.owner
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.source
     *
     * @return the value of tbl_contacts.source
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.source
     *
     * @param source the value for tbl_contacts.source
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.customer_id
     *
     * @return the value of tbl_contacts.customer_id
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getCustomer_id() {
        return customer_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.customer_id
     *
     * @param customer_id the value for tbl_contacts.customer_id
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setCustomer_id(String customer_id) {
        this.customer_id = customer_id == null ? null : customer_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.fullname
     *
     * @return the value of tbl_contacts.fullname
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.fullname
     *
     * @param fullname the value for tbl_contacts.fullname
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.appellation
     *
     * @return the value of tbl_contacts.appellation
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getAppellation() {
        return appellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.appellation
     *
     * @param appellation the value for tbl_contacts.appellation
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setAppellation(String appellation) {
        this.appellation = appellation == null ? null : appellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.email
     *
     * @return the value of tbl_contacts.email
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.email
     *
     * @param email the value for tbl_contacts.email
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.mphone
     *
     * @return the value of tbl_contacts.mphone
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getMphone() {
        return mphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.mphone
     *
     * @param mphone the value for tbl_contacts.mphone
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setMphone(String mphone) {
        this.mphone = mphone == null ? null : mphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.job
     *
     * @return the value of tbl_contacts.job
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.job
     *
     * @param job the value for tbl_contacts.job
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.create_by
     *
     * @return the value of tbl_contacts.create_by
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getCreate_by() {
        return create_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.create_by
     *
     * @param create_by the value for tbl_contacts.create_by
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setCreate_by(String create_by) {
        this.create_by = create_by == null ? null : create_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.create_time
     *
     * @return the value of tbl_contacts.create_time
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.create_time
     *
     * @param create_time the value for tbl_contacts.create_time
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setCreate_time(String create_time) {
        this.create_time = create_time == null ? null : create_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.edit_by
     *
     * @return the value of tbl_contacts.edit_by
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getEdit_by() {
        return edit_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.edit_by
     *
     * @param edit_by the value for tbl_contacts.edit_by
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setEdit_by(String edit_by) {
        this.edit_by = edit_by == null ? null : edit_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.edit_time
     *
     * @return the value of tbl_contacts.edit_time
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getEdit_time() {
        return edit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.edit_time
     *
     * @param edit_time the value for tbl_contacts.edit_time
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setEdit_time(String edit_time) {
        this.edit_time = edit_time == null ? null : edit_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.description
     *
     * @return the value of tbl_contacts.description
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.description
     *
     * @param description the value for tbl_contacts.description
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.contact_summary
     *
     * @return the value of tbl_contacts.contact_summary
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getContact_summary() {
        return contact_summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.contact_summary
     *
     * @param contact_summary the value for tbl_contacts.contact_summary
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setContact_summary(String contact_summary) {
        this.contact_summary = contact_summary == null ? null : contact_summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.next_contact_time
     *
     * @return the value of tbl_contacts.next_contact_time
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getNext_contact_time() {
        return next_contact_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.next_contact_time
     *
     * @param next_contact_time the value for tbl_contacts.next_contact_time
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setNext_contact_time(String next_contact_time) {
        this.next_contact_time = next_contact_time == null ? null : next_contact_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.address
     *
     * @return the value of tbl_contacts.address
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.address
     *
     * @param address the value for tbl_contacts.address
     *
     * @mbggenerated Thu Aug 11 13:21:54 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}