package com.zw.domain;

public class ContactsRemark {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.id
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.note_content
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    private String note_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.create_by
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    private String create_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.create_time
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    private String create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.edit_by
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    private String edit_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.edit_time
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    private String edit_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.edit_flag
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    private String edit_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.contacts_id
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    private String contacts_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.id
     *
     * @return the value of tbl_contacts_remark.id
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.id
     *
     * @param id the value for tbl_contacts_remark.id
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.note_content
     *
     * @return the value of tbl_contacts_remark.note_content
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public String getNote_content() {
        return note_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.note_content
     *
     * @param note_content the value for tbl_contacts_remark.note_content
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public void setNote_content(String note_content) {
        this.note_content = note_content == null ? null : note_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.create_by
     *
     * @return the value of tbl_contacts_remark.create_by
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public String getCreate_by() {
        return create_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.create_by
     *
     * @param create_by the value for tbl_contacts_remark.create_by
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public void setCreate_by(String create_by) {
        this.create_by = create_by == null ? null : create_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.create_time
     *
     * @return the value of tbl_contacts_remark.create_time
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public String getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.create_time
     *
     * @param create_time the value for tbl_contacts_remark.create_time
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public void setCreate_time(String create_time) {
        this.create_time = create_time == null ? null : create_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.edit_by
     *
     * @return the value of tbl_contacts_remark.edit_by
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public String getEdit_by() {
        return edit_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.edit_by
     *
     * @param edit_by the value for tbl_contacts_remark.edit_by
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public void setEdit_by(String edit_by) {
        this.edit_by = edit_by == null ? null : edit_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.edit_time
     *
     * @return the value of tbl_contacts_remark.edit_time
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public String getEdit_time() {
        return edit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.edit_time
     *
     * @param edit_time the value for tbl_contacts_remark.edit_time
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public void setEdit_time(String edit_time) {
        this.edit_time = edit_time == null ? null : edit_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.edit_flag
     *
     * @return the value of tbl_contacts_remark.edit_flag
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public String getEdit_flag() {
        return edit_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.edit_flag
     *
     * @param edit_flag the value for tbl_contacts_remark.edit_flag
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public void setEdit_flag(String edit_flag) {
        this.edit_flag = edit_flag == null ? null : edit_flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.contacts_id
     *
     * @return the value of tbl_contacts_remark.contacts_id
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public String getContacts_id() {
        return contacts_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.contacts_id
     *
     * @param contacts_id the value for tbl_contacts_remark.contacts_id
     *
     * @mbggenerated Thu Aug 11 14:15:30 CST 2022
     */
    public void setContacts_id(String contacts_id) {
        this.contacts_id = contacts_id == null ? null : contacts_id.trim();
    }
}