package com.zw.domain;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.id
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.owner
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.name
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.website
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.phone
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.create_by
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String create_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.create_time
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.edit_by
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String edit_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.edit_time
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String edit_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.contact_summary
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String contact_summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.next_contact_time
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String next_contact_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.description
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.address
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.id
     *
     * @return the value of tbl_customer.id
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.id
     *
     * @param id the value for tbl_customer.id
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.owner
     *
     * @return the value of tbl_customer.owner
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.owner
     *
     * @param owner the value for tbl_customer.owner
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.name
     *
     * @return the value of tbl_customer.name
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.name
     *
     * @param name the value for tbl_customer.name
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.website
     *
     * @return the value of tbl_customer.website
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.website
     *
     * @param website the value for tbl_customer.website
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.phone
     *
     * @return the value of tbl_customer.phone
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.phone
     *
     * @param phone the value for tbl_customer.phone
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.create_by
     *
     * @return the value of tbl_customer.create_by
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getCreate_by() {
        return create_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.create_by
     *
     * @param create_by the value for tbl_customer.create_by
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setCreate_by(String create_by) {
        this.create_by = create_by == null ? null : create_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.create_time
     *
     * @return the value of tbl_customer.create_time
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.create_time
     *
     * @param create_time the value for tbl_customer.create_time
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setCreate_time(String create_time) {
        this.create_time = create_time == null ? null : create_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.edit_by
     *
     * @return the value of tbl_customer.edit_by
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getEdit_by() {
        return edit_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.edit_by
     *
     * @param edit_by the value for tbl_customer.edit_by
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setEdit_by(String edit_by) {
        this.edit_by = edit_by == null ? null : edit_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.edit_time
     *
     * @return the value of tbl_customer.edit_time
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getEdit_time() {
        return edit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.edit_time
     *
     * @param edit_time the value for tbl_customer.edit_time
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setEdit_time(String edit_time) {
        this.edit_time = edit_time == null ? null : edit_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.contact_summary
     *
     * @return the value of tbl_customer.contact_summary
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getContact_summary() {
        return contact_summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.contact_summary
     *
     * @param contact_summary the value for tbl_customer.contact_summary
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setContact_summary(String contact_summary) {
        this.contact_summary = contact_summary == null ? null : contact_summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.next_contact_time
     *
     * @return the value of tbl_customer.next_contact_time
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getNext_contact_time() {
        return next_contact_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.next_contact_time
     *
     * @param next_contact_time the value for tbl_customer.next_contact_time
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setNext_contact_time(String next_contact_time) {
        this.next_contact_time = next_contact_time == null ? null : next_contact_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.description
     *
     * @return the value of tbl_customer.description
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.description
     *
     * @param description the value for tbl_customer.description
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.address
     *
     * @return the value of tbl_customer.address
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.address
     *
     * @param address the value for tbl_customer.address
     *
     * @mbggenerated Wed Aug 10 21:11:34 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}