package com.zw.domain;

public class DivValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.id
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.text
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.order_no
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    private String order_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.type_code
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    private String type_code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_value.id
     *
     * @return the value of tbl_dic_value.id
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_value.id
     *
     * @param id the value for tbl_dic_value.id
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_value.value
     *
     * @return the value of tbl_dic_value.value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_value.value
     *
     * @param value the value for tbl_dic_value.value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_value.text
     *
     * @return the value of tbl_dic_value.text
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_value.text
     *
     * @param text the value for tbl_dic_value.text
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_value.order_no
     *
     * @return the value of tbl_dic_value.order_no
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    public String getOrder_no() {
        return order_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_value.order_no
     *
     * @param order_no the value for tbl_dic_value.order_no
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    public void setOrder_no(String order_no) {
        this.order_no = order_no == null ? null : order_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_value.type_code
     *
     * @return the value of tbl_dic_value.type_code
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    public String getType_code() {
        return type_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_value.type_code
     *
     * @param type_code the value for tbl_dic_value.type_code
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    public void setType_code(String type_code) {
        this.type_code = type_code == null ? null : type_code.trim();
    }
}