package com.zw.domain;

public class TranHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.id
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.stage
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    private String stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.money
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.expected_date
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    private String expected_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.create_time
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    private String create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.create_by
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    private String create_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.tran_id
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    private String tran_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.id
     *
     * @return the value of tbl_tran_history.id
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.id
     *
     * @param id the value for tbl_tran_history.id
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.stage
     *
     * @return the value of tbl_tran_history.stage
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public String getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.stage
     *
     * @param stage the value for tbl_tran_history.stage
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public void setStage(String stage) {
        this.stage = stage == null ? null : stage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.money
     *
     * @return the value of tbl_tran_history.money
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.money
     *
     * @param money the value for tbl_tran_history.money
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.expected_date
     *
     * @return the value of tbl_tran_history.expected_date
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public String getExpected_date() {
        return expected_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.expected_date
     *
     * @param expected_date the value for tbl_tran_history.expected_date
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public void setExpected_date(String expected_date) {
        this.expected_date = expected_date == null ? null : expected_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.create_time
     *
     * @return the value of tbl_tran_history.create_time
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public String getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.create_time
     *
     * @param create_time the value for tbl_tran_history.create_time
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public void setCreate_time(String create_time) {
        this.create_time = create_time == null ? null : create_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.create_by
     *
     * @return the value of tbl_tran_history.create_by
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public String getCreate_by() {
        return create_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.create_by
     *
     * @param create_by the value for tbl_tran_history.create_by
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public void setCreate_by(String create_by) {
        this.create_by = create_by == null ? null : create_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.tran_id
     *
     * @return the value of tbl_tran_history.tran_id
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public String getTran_id() {
        return tran_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.tran_id
     *
     * @param tran_id the value for tbl_tran_history.tran_id
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    public void setTran_id(String tran_id) {
        this.tran_id = tran_id == null ? null : tran_id.trim();
    }
}