package com.zw.domain;

public class Tran {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.owner
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.money
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.name
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.expected_date
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String expected_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.customer_id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String customer_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.stage
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.type
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.source
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.activity_id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String activity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.contacts_id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String contacts_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.create_by
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String create_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.create_time
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.edit_by
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String edit_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.edit_time
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String edit_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.description
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.contact_summary
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String contact_summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran.next_contact_time
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    private String next_contact_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.id
     *
     * @return the value of tbl_tran.id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.id
     *
     * @param id the value for tbl_tran.id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.owner
     *
     * @return the value of tbl_tran.owner
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.owner
     *
     * @param owner the value for tbl_tran.owner
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.money
     *
     * @return the value of tbl_tran.money
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.money
     *
     * @param money the value for tbl_tran.money
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.name
     *
     * @return the value of tbl_tran.name
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.name
     *
     * @param name the value for tbl_tran.name
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.expected_date
     *
     * @return the value of tbl_tran.expected_date
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getExpected_date() {
        return expected_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.expected_date
     *
     * @param expected_date the value for tbl_tran.expected_date
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setExpected_date(String expected_date) {
        this.expected_date = expected_date == null ? null : expected_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.customer_id
     *
     * @return the value of tbl_tran.customer_id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getCustomer_id() {
        return customer_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.customer_id
     *
     * @param customer_id the value for tbl_tran.customer_id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setCustomer_id(String customer_id) {
        this.customer_id = customer_id == null ? null : customer_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.stage
     *
     * @return the value of tbl_tran.stage
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.stage
     *
     * @param stage the value for tbl_tran.stage
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setStage(String stage) {
        this.stage = stage == null ? null : stage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.type
     *
     * @return the value of tbl_tran.type
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.type
     *
     * @param type the value for tbl_tran.type
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.source
     *
     * @return the value of tbl_tran.source
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.source
     *
     * @param source the value for tbl_tran.source
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.activity_id
     *
     * @return the value of tbl_tran.activity_id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getActivity_id() {
        return activity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.activity_id
     *
     * @param activity_id the value for tbl_tran.activity_id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setActivity_id(String activity_id) {
        this.activity_id = activity_id == null ? null : activity_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.contacts_id
     *
     * @return the value of tbl_tran.contacts_id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getContacts_id() {
        return contacts_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.contacts_id
     *
     * @param contacts_id the value for tbl_tran.contacts_id
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setContacts_id(String contacts_id) {
        this.contacts_id = contacts_id == null ? null : contacts_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.create_by
     *
     * @return the value of tbl_tran.create_by
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getCreate_by() {
        return create_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.create_by
     *
     * @param create_by the value for tbl_tran.create_by
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setCreate_by(String create_by) {
        this.create_by = create_by == null ? null : create_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.create_time
     *
     * @return the value of tbl_tran.create_time
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.create_time
     *
     * @param create_time the value for tbl_tran.create_time
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setCreate_time(String create_time) {
        this.create_time = create_time == null ? null : create_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.edit_by
     *
     * @return the value of tbl_tran.edit_by
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getEdit_by() {
        return edit_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.edit_by
     *
     * @param edit_by the value for tbl_tran.edit_by
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setEdit_by(String edit_by) {
        this.edit_by = edit_by == null ? null : edit_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.edit_time
     *
     * @return the value of tbl_tran.edit_time
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getEdit_time() {
        return edit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.edit_time
     *
     * @param edit_time the value for tbl_tran.edit_time
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setEdit_time(String edit_time) {
        this.edit_time = edit_time == null ? null : edit_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.description
     *
     * @return the value of tbl_tran.description
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.description
     *
     * @param description the value for tbl_tran.description
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.contact_summary
     *
     * @return the value of tbl_tran.contact_summary
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getContact_summary() {
        return contact_summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.contact_summary
     *
     * @param contact_summary the value for tbl_tran.contact_summary
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setContact_summary(String contact_summary) {
        this.contact_summary = contact_summary == null ? null : contact_summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran.next_contact_time
     *
     * @return the value of tbl_tran.next_contact_time
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public String getNext_contact_time() {
        return next_contact_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran.next_contact_time
     *
     * @param next_contact_time the value for tbl_tran.next_contact_time
     *
     * @mbggenerated Thu Aug 11 15:12:44 CST 2022
     */
    public void setNext_contact_time(String next_contact_time) {
        this.next_contact_time = next_contact_time == null ? null : next_contact_time.trim();
    }
}