package com.zw.domain;

import java.util.ArrayList;
import java.util.List;

public class userExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public userExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLogin_actIsNull() {
            addCriterion("login_act is null");
            return (Criteria) this;
        }

        public Criteria andLogin_actIsNotNull() {
            addCriterion("login_act is not null");
            return (Criteria) this;
        }

        public Criteria andLogin_actEqualTo(String value) {
            addCriterion("login_act =", value, "login_act");
            return (Criteria) this;
        }

        public Criteria andLogin_actNotEqualTo(String value) {
            addCriterion("login_act <>", value, "login_act");
            return (Criteria) this;
        }

        public Criteria andLogin_actGreaterThan(String value) {
            addCriterion("login_act >", value, "login_act");
            return (Criteria) this;
        }

        public Criteria andLogin_actGreaterThanOrEqualTo(String value) {
            addCriterion("login_act >=", value, "login_act");
            return (Criteria) this;
        }

        public Criteria andLogin_actLessThan(String value) {
            addCriterion("login_act <", value, "login_act");
            return (Criteria) this;
        }

        public Criteria andLogin_actLessThanOrEqualTo(String value) {
            addCriterion("login_act <=", value, "login_act");
            return (Criteria) this;
        }

        public Criteria andLogin_actLike(String value) {
            addCriterion("login_act like", value, "login_act");
            return (Criteria) this;
        }

        public Criteria andLogin_actNotLike(String value) {
            addCriterion("login_act not like", value, "login_act");
            return (Criteria) this;
        }

        public Criteria andLogin_actIn(List<String> values) {
            addCriterion("login_act in", values, "login_act");
            return (Criteria) this;
        }

        public Criteria andLogin_actNotIn(List<String> values) {
            addCriterion("login_act not in", values, "login_act");
            return (Criteria) this;
        }

        public Criteria andLogin_actBetween(String value1, String value2) {
            addCriterion("login_act between", value1, value2, "login_act");
            return (Criteria) this;
        }

        public Criteria andLogin_actNotBetween(String value1, String value2) {
            addCriterion("login_act not between", value1, value2, "login_act");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdIsNull() {
            addCriterion("login_pwd is null");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdIsNotNull() {
            addCriterion("login_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdEqualTo(String value) {
            addCriterion("login_pwd =", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdNotEqualTo(String value) {
            addCriterion("login_pwd <>", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdGreaterThan(String value) {
            addCriterion("login_pwd >", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdGreaterThanOrEqualTo(String value) {
            addCriterion("login_pwd >=", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdLessThan(String value) {
            addCriterion("login_pwd <", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdLessThanOrEqualTo(String value) {
            addCriterion("login_pwd <=", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdLike(String value) {
            addCriterion("login_pwd like", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdNotLike(String value) {
            addCriterion("login_pwd not like", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdIn(List<String> values) {
            addCriterion("login_pwd in", values, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdNotIn(List<String> values) {
            addCriterion("login_pwd not in", values, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdBetween(String value1, String value2) {
            addCriterion("login_pwd between", value1, value2, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdNotBetween(String value1, String value2) {
            addCriterion("login_pwd not between", value1, value2, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andExpire_timeIsNull() {
            addCriterion("expire_time is null");
            return (Criteria) this;
        }

        public Criteria andExpire_timeIsNotNull() {
            addCriterion("expire_time is not null");
            return (Criteria) this;
        }

        public Criteria andExpire_timeEqualTo(String value) {
            addCriterion("expire_time =", value, "expire_time");
            return (Criteria) this;
        }

        public Criteria andExpire_timeNotEqualTo(String value) {
            addCriterion("expire_time <>", value, "expire_time");
            return (Criteria) this;
        }

        public Criteria andExpire_timeGreaterThan(String value) {
            addCriterion("expire_time >", value, "expire_time");
            return (Criteria) this;
        }

        public Criteria andExpire_timeGreaterThanOrEqualTo(String value) {
            addCriterion("expire_time >=", value, "expire_time");
            return (Criteria) this;
        }

        public Criteria andExpire_timeLessThan(String value) {
            addCriterion("expire_time <", value, "expire_time");
            return (Criteria) this;
        }

        public Criteria andExpire_timeLessThanOrEqualTo(String value) {
            addCriterion("expire_time <=", value, "expire_time");
            return (Criteria) this;
        }

        public Criteria andExpire_timeLike(String value) {
            addCriterion("expire_time like", value, "expire_time");
            return (Criteria) this;
        }

        public Criteria andExpire_timeNotLike(String value) {
            addCriterion("expire_time not like", value, "expire_time");
            return (Criteria) this;
        }

        public Criteria andExpire_timeIn(List<String> values) {
            addCriterion("expire_time in", values, "expire_time");
            return (Criteria) this;
        }

        public Criteria andExpire_timeNotIn(List<String> values) {
            addCriterion("expire_time not in", values, "expire_time");
            return (Criteria) this;
        }

        public Criteria andExpire_timeBetween(String value1, String value2) {
            addCriterion("expire_time between", value1, value2, "expire_time");
            return (Criteria) this;
        }

        public Criteria andExpire_timeNotBetween(String value1, String value2) {
            addCriterion("expire_time not between", value1, value2, "expire_time");
            return (Criteria) this;
        }

        public Criteria andLock_stateIsNull() {
            addCriterion("lock_state is null");
            return (Criteria) this;
        }

        public Criteria andLock_stateIsNotNull() {
            addCriterion("lock_state is not null");
            return (Criteria) this;
        }

        public Criteria andLock_stateEqualTo(String value) {
            addCriterion("lock_state =", value, "lock_state");
            return (Criteria) this;
        }

        public Criteria andLock_stateNotEqualTo(String value) {
            addCriterion("lock_state <>", value, "lock_state");
            return (Criteria) this;
        }

        public Criteria andLock_stateGreaterThan(String value) {
            addCriterion("lock_state >", value, "lock_state");
            return (Criteria) this;
        }

        public Criteria andLock_stateGreaterThanOrEqualTo(String value) {
            addCriterion("lock_state >=", value, "lock_state");
            return (Criteria) this;
        }

        public Criteria andLock_stateLessThan(String value) {
            addCriterion("lock_state <", value, "lock_state");
            return (Criteria) this;
        }

        public Criteria andLock_stateLessThanOrEqualTo(String value) {
            addCriterion("lock_state <=", value, "lock_state");
            return (Criteria) this;
        }

        public Criteria andLock_stateLike(String value) {
            addCriterion("lock_state like", value, "lock_state");
            return (Criteria) this;
        }

        public Criteria andLock_stateNotLike(String value) {
            addCriterion("lock_state not like", value, "lock_state");
            return (Criteria) this;
        }

        public Criteria andLock_stateIn(List<String> values) {
            addCriterion("lock_state in", values, "lock_state");
            return (Criteria) this;
        }

        public Criteria andLock_stateNotIn(List<String> values) {
            addCriterion("lock_state not in", values, "lock_state");
            return (Criteria) this;
        }

        public Criteria andLock_stateBetween(String value1, String value2) {
            addCriterion("lock_state between", value1, value2, "lock_state");
            return (Criteria) this;
        }

        public Criteria andLock_stateNotBetween(String value1, String value2) {
            addCriterion("lock_state not between", value1, value2, "lock_state");
            return (Criteria) this;
        }

        public Criteria andDeptnoIsNull() {
            addCriterion("deptno is null");
            return (Criteria) this;
        }

        public Criteria andDeptnoIsNotNull() {
            addCriterion("deptno is not null");
            return (Criteria) this;
        }

        public Criteria andDeptnoEqualTo(String value) {
            addCriterion("deptno =", value, "deptno");
            return (Criteria) this;
        }

        public Criteria andDeptnoNotEqualTo(String value) {
            addCriterion("deptno <>", value, "deptno");
            return (Criteria) this;
        }

        public Criteria andDeptnoGreaterThan(String value) {
            addCriterion("deptno >", value, "deptno");
            return (Criteria) this;
        }

        public Criteria andDeptnoGreaterThanOrEqualTo(String value) {
            addCriterion("deptno >=", value, "deptno");
            return (Criteria) this;
        }

        public Criteria andDeptnoLessThan(String value) {
            addCriterion("deptno <", value, "deptno");
            return (Criteria) this;
        }

        public Criteria andDeptnoLessThanOrEqualTo(String value) {
            addCriterion("deptno <=", value, "deptno");
            return (Criteria) this;
        }

        public Criteria andDeptnoLike(String value) {
            addCriterion("deptno like", value, "deptno");
            return (Criteria) this;
        }

        public Criteria andDeptnoNotLike(String value) {
            addCriterion("deptno not like", value, "deptno");
            return (Criteria) this;
        }

        public Criteria andDeptnoIn(List<String> values) {
            addCriterion("deptno in", values, "deptno");
            return (Criteria) this;
        }

        public Criteria andDeptnoNotIn(List<String> values) {
            addCriterion("deptno not in", values, "deptno");
            return (Criteria) this;
        }

        public Criteria andDeptnoBetween(String value1, String value2) {
            addCriterion("deptno between", value1, value2, "deptno");
            return (Criteria) this;
        }

        public Criteria andDeptnoNotBetween(String value1, String value2) {
            addCriterion("deptno not between", value1, value2, "deptno");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsIsNull() {
            addCriterion("allow_ips is null");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsIsNotNull() {
            addCriterion("allow_ips is not null");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsEqualTo(String value) {
            addCriterion("allow_ips =", value, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsNotEqualTo(String value) {
            addCriterion("allow_ips <>", value, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsGreaterThan(String value) {
            addCriterion("allow_ips >", value, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsGreaterThanOrEqualTo(String value) {
            addCriterion("allow_ips >=", value, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsLessThan(String value) {
            addCriterion("allow_ips <", value, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsLessThanOrEqualTo(String value) {
            addCriterion("allow_ips <=", value, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsLike(String value) {
            addCriterion("allow_ips like", value, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsNotLike(String value) {
            addCriterion("allow_ips not like", value, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsIn(List<String> values) {
            addCriterion("allow_ips in", values, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsNotIn(List<String> values) {
            addCriterion("allow_ips not in", values, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsBetween(String value1, String value2) {
            addCriterion("allow_ips between", value1, value2, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andAllow_ipsNotBetween(String value1, String value2) {
            addCriterion("allow_ips not between", value1, value2, "allow_ips");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("createTime like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("createTime not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreate_byIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreate_byIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_byEqualTo(String value) {
            addCriterion("create_by =", value, "create_by");
            return (Criteria) this;
        }

        public Criteria andCreate_byNotEqualTo(String value) {
            addCriterion("create_by <>", value, "create_by");
            return (Criteria) this;
        }

        public Criteria andCreate_byGreaterThan(String value) {
            addCriterion("create_by >", value, "create_by");
            return (Criteria) this;
        }

        public Criteria andCreate_byGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "create_by");
            return (Criteria) this;
        }

        public Criteria andCreate_byLessThan(String value) {
            addCriterion("create_by <", value, "create_by");
            return (Criteria) this;
        }

        public Criteria andCreate_byLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "create_by");
            return (Criteria) this;
        }

        public Criteria andCreate_byLike(String value) {
            addCriterion("create_by like", value, "create_by");
            return (Criteria) this;
        }

        public Criteria andCreate_byNotLike(String value) {
            addCriterion("create_by not like", value, "create_by");
            return (Criteria) this;
        }

        public Criteria andCreate_byIn(List<String> values) {
            addCriterion("create_by in", values, "create_by");
            return (Criteria) this;
        }

        public Criteria andCreate_byNotIn(List<String> values) {
            addCriterion("create_by not in", values, "create_by");
            return (Criteria) this;
        }

        public Criteria andCreate_byBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "create_by");
            return (Criteria) this;
        }

        public Criteria andCreate_byNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "create_by");
            return (Criteria) this;
        }

        public Criteria andEdit_timeIsNull() {
            addCriterion("edit_time is null");
            return (Criteria) this;
        }

        public Criteria andEdit_timeIsNotNull() {
            addCriterion("edit_time is not null");
            return (Criteria) this;
        }

        public Criteria andEdit_timeEqualTo(String value) {
            addCriterion("edit_time =", value, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_timeNotEqualTo(String value) {
            addCriterion("edit_time <>", value, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_timeGreaterThan(String value) {
            addCriterion("edit_time >", value, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_timeGreaterThanOrEqualTo(String value) {
            addCriterion("edit_time >=", value, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_timeLessThan(String value) {
            addCriterion("edit_time <", value, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_timeLessThanOrEqualTo(String value) {
            addCriterion("edit_time <=", value, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_timeLike(String value) {
            addCriterion("edit_time like", value, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_timeNotLike(String value) {
            addCriterion("edit_time not like", value, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_timeIn(List<String> values) {
            addCriterion("edit_time in", values, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_timeNotIn(List<String> values) {
            addCriterion("edit_time not in", values, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_timeBetween(String value1, String value2) {
            addCriterion("edit_time between", value1, value2, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_timeNotBetween(String value1, String value2) {
            addCriterion("edit_time not between", value1, value2, "edit_time");
            return (Criteria) this;
        }

        public Criteria andEdit_byIsNull() {
            addCriterion("edit_by is null");
            return (Criteria) this;
        }

        public Criteria andEdit_byIsNotNull() {
            addCriterion("edit_by is not null");
            return (Criteria) this;
        }

        public Criteria andEdit_byEqualTo(String value) {
            addCriterion("edit_by =", value, "edit_by");
            return (Criteria) this;
        }

        public Criteria andEdit_byNotEqualTo(String value) {
            addCriterion("edit_by <>", value, "edit_by");
            return (Criteria) this;
        }

        public Criteria andEdit_byGreaterThan(String value) {
            addCriterion("edit_by >", value, "edit_by");
            return (Criteria) this;
        }

        public Criteria andEdit_byGreaterThanOrEqualTo(String value) {
            addCriterion("edit_by >=", value, "edit_by");
            return (Criteria) this;
        }

        public Criteria andEdit_byLessThan(String value) {
            addCriterion("edit_by <", value, "edit_by");
            return (Criteria) this;
        }

        public Criteria andEdit_byLessThanOrEqualTo(String value) {
            addCriterion("edit_by <=", value, "edit_by");
            return (Criteria) this;
        }

        public Criteria andEdit_byLike(String value) {
            addCriterion("edit_by like", value, "edit_by");
            return (Criteria) this;
        }

        public Criteria andEdit_byNotLike(String value) {
            addCriterion("edit_by not like", value, "edit_by");
            return (Criteria) this;
        }

        public Criteria andEdit_byIn(List<String> values) {
            addCriterion("edit_by in", values, "edit_by");
            return (Criteria) this;
        }

        public Criteria andEdit_byNotIn(List<String> values) {
            addCriterion("edit_by not in", values, "edit_by");
            return (Criteria) this;
        }

        public Criteria andEdit_byBetween(String value1, String value2) {
            addCriterion("edit_by between", value1, value2, "edit_by");
            return (Criteria) this;
        }

        public Criteria andEdit_byNotBetween(String value1, String value2) {
            addCriterion("edit_by not between", value1, value2, "edit_by");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_user
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 11 16:23:21 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}