package com.zw.domain;

public class user {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.id
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.login_act
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String login_act;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.name
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.login_pwd
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String login_pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.email
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.expire_time
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String expire_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.lock_state
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String lock_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.deptno
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String deptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.allow_ips
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String allow_ips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.createTime
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.create_by
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String create_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.edit_time
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String edit_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.edit_by
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    private String edit_by;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.id
     *
     * @return the value of tbl_user.id
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.id
     *
     * @param id the value for tbl_user.id
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.login_act
     *
     * @return the value of tbl_user.login_act
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getLogin_act() {
        return login_act;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.login_act
     *
     * @param login_act the value for tbl_user.login_act
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setLogin_act(String login_act) {
        this.login_act = login_act == null ? null : login_act.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.name
     *
     * @return the value of tbl_user.name
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.name
     *
     * @param name the value for tbl_user.name
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.login_pwd
     *
     * @return the value of tbl_user.login_pwd
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getLogin_pwd() {
        return login_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.login_pwd
     *
     * @param login_pwd the value for tbl_user.login_pwd
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setLogin_pwd(String login_pwd) {
        this.login_pwd = login_pwd == null ? null : login_pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.email
     *
     * @return the value of tbl_user.email
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.email
     *
     * @param email the value for tbl_user.email
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.expire_time
     *
     * @return the value of tbl_user.expire_time
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getExpire_time() {
        return expire_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.expire_time
     *
     * @param expire_time the value for tbl_user.expire_time
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setExpire_time(String expire_time) {
        this.expire_time = expire_time == null ? null : expire_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.lock_state
     *
     * @return the value of tbl_user.lock_state
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getLock_state() {
        return lock_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.lock_state
     *
     * @param lock_state the value for tbl_user.lock_state
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setLock_state(String lock_state) {
        this.lock_state = lock_state == null ? null : lock_state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.deptno
     *
     * @return the value of tbl_user.deptno
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.deptno
     *
     * @param deptno the value for tbl_user.deptno
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setDeptno(String deptno) {
        this.deptno = deptno == null ? null : deptno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.allow_ips
     *
     * @return the value of tbl_user.allow_ips
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getAllow_ips() {
        return allow_ips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.allow_ips
     *
     * @param allow_ips the value for tbl_user.allow_ips
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setAllow_ips(String allow_ips) {
        this.allow_ips = allow_ips == null ? null : allow_ips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.createTime
     *
     * @return the value of tbl_user.createTime
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.createTime
     *
     * @param createTime the value for tbl_user.createTime
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.create_by
     *
     * @return the value of tbl_user.create_by
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getCreate_by() {
        return create_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.create_by
     *
     * @param create_by the value for tbl_user.create_by
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setCreate_by(String create_by) {
        this.create_by = create_by == null ? null : create_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.edit_time
     *
     * @return the value of tbl_user.edit_time
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getEdit_time() {
        return edit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.edit_time
     *
     * @param edit_time the value for tbl_user.edit_time
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setEdit_time(String edit_time) {
        this.edit_time = edit_time == null ? null : edit_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.edit_by
     *
     * @return the value of tbl_user.edit_by
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public String getEdit_by() {
        return edit_by;
    }

    @Override
    public String toString() {
        return "user{" +
                "id='" + id + '\'' +
                ", login_act='" + login_act + '\'' +
                ", name='" + name + '\'' +
                ", login_pwd='" + login_pwd + '\'' +
                ", email='" + email + '\'' +
                ", expire_time='" + expire_time + '\'' +
                ", lock_state='" + lock_state + '\'' +
                ", deptno='" + deptno + '\'' +
                ", allow_ips='" + allow_ips + '\'' +
                ", createTime='" + createTime + '\'' +
                ", create_by='" + create_by + '\'' +
                ", edit_time='" + edit_time + '\'' +
                ", edit_by='" + edit_by + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.edit_by
     *
     * @param edit_by the value for tbl_user.edit_by
     *
     * @mbggenerated Sat Jun 11 16:23:21 CST 2022
     */
    public void setEdit_by(String edit_by) {
        this.edit_by = edit_by == null ? null : edit_by.trim();
    }
}