package com.zw.dao;

import com.zw.domain.activity;
import com.zw.domain.activityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface activityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    int countByExample(activityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    int deleteByExample(activityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    int insert(activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    int insertSelective(activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    List<activity> selectByExample(activityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    activity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    int updateByExampleSelective(@Param("record") activity record, @Param("example") activityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    int updateByExample(@Param("record") activity record, @Param("example") activityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    int updateByPrimaryKeySelective(activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 16 16:09:45 CST 2022
     */
    int updateByPrimaryKey(activity record);
}