package com.zw.dao;

import com.zw.domain.Clue;
import com.zw.domain.ClueExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ClueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    int countByExample(ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    int deleteByExample(ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    int insert(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    int insertSelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    List<Clue> selectByExample(ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    Clue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    int updateByExampleSelective(@Param("record") Clue record, @Param("example") ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    int updateByExample(@Param("record") Clue record, @Param("example") ClueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    int updateByPrimaryKeySelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Mon Aug 08 13:34:14 CST 2022
     */
    int updateByPrimaryKey(Clue record);

    int insertClue(Clue clue);

    List<Clue> selectClue(Map<String,Object> map);
    int selectCon(Map<String,Object> map);
    Clue selectClueDetail(String id);
}