package com.zw.dao;

import com.zw.domain.DivValue;
import com.zw.domain.DivValueExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DivValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    int countByExample(DivValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    int deleteByExample(DivValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    int insert(DivValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    int insertSelective(DivValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    List<DivValue> selectByExample(DivValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    DivValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    int updateByExampleSelective(@Param("record") DivValue record, @Param("example") DivValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    int updateByExample(@Param("record") DivValue record, @Param("example") DivValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    int updateByPrimaryKeySelective(DivValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sun Aug 07 21:05:07 CST 2022
     */
    int updateByPrimaryKey(DivValue record);
    //查询
    List<DivValue> selectDivValue(String typeCode);
}