package com.zw.dao;

import com.zw.domain.TranHistory;
import com.zw.domain.TranHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TranHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    int countByExample(TranHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    int deleteByExample(TranHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    int insert(TranHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    int insertSelective(TranHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    List<TranHistory> selectByExample(TranHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    TranHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    int updateByExampleSelective(@Param("record") TranHistory record, @Param("example") TranHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    int updateByExample(@Param("record") TranHistory record, @Param("example") TranHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    int updateByPrimaryKeySelective(TranHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Mon Aug 15 19:22:22 CST 2022
     */
    int updateByPrimaryKey(TranHistory record);

    int insertTranHistory(TranHistory tranHistory);

    List<TranHistory> selectTranHitstory(String id);
}